apiVersion: v1
kind: Namespace
metadata:
  name: px-log-generator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: px-log-generator
data:
  vector.toml: |
    [sources.demo]
    type = "demo_logs"
    format = "json"

    [sinks.json_output]
    type = "file"
    inputs = ["demo"]
    path = "/var/log/px-log-generator.json"
    encoding.codec = "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-logrotate-config
  namespace: px-log-generator
data:
  logrotate.conf: |
    /var/log/px-log-generator.json {
        size 30M
        copytruncate
        rotate 5
        compress
        missingok
        notifempty
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: px-log-generator
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      volumes:
        - name: log-storage
          hostPath:
            path: /var/log
            type: Directory
        - name: logrotate-config
          configMap:
            name: vector-logrotate-config
        - name: config-volume
          configMap:
            name: vector-config
      initContainers:
        - name: cleanup
          image: busybox
          command: ["/bin/sh", "-c", "truncate -s0 /var/log/px-log-generator.json"]
          volumeMounts:
            - name: log-storage
              mountPath: /var/log
      containers:
        - name: vector
          image: timberio/vector@sha256:f8933ff1a3ec08df45abc6130947938d98dc85792a25592ec1aa6fe83a7f562c  # 0.44.0-debian
          args: ["--config", "/etc/vector/vector.toml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/vector
            - name: log-storage
              mountPath: /var/log
        - name: logrotate
          image: vitess/logrotate@sha256:ba0f99827d0e2d0bda86230ff6666e75383d93babcbc6c803c4d41396214f312  # v21.0.2-bookworm
          volumeMounts:
            - name: logrotate-config
              mountPath: /vt/logrotate.conf
              subPath: logrotate.conf
            - name: log-storage
              mountPath: /var/log
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
