---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pl-oauth-config
data:
  PL_OAUTH_PROVIDER: hydra
  PL_AUTH_URI: /oauth/hydra
  PL_AUTH_CLIENT_ID: 07ab750f-9b37-4df8-b107-a0d112bcf329
  PL_AUTH_EMAIL_PASSWORD_CONN: ""
