---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pl-oauth-config
data:
  PL_OAUTH_PROVIDER: hydra
  PL_AUTH_URI: /oauth/hydra
  PL_AUTH_CLIENT_ID: 5d8827bd-a958-415b-a541-3f68ab06e9b5
  PL_AUTH_EMAIL_PASSWORD_CONN: ""
