apiVersion: v1
kind: Namespace
metadata:
  name: px-finagle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: finagle-client
  name: finagle-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: finagle-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: finagle-client
    spec:
      containers:
      - args:
        - client/run
        image: gcr.io/pixie-prod/demos/finagle/client:1.0
        name: finagle-client
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: finagle-server
  name: finagle-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: finagle-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: finagle-server
    spec:
      containers:
      - image: gcr.io/pixie-prod/demos/finagle/server:1.0
        name: finagle-server
        resources: {}
      restartPolicy: Always
status: {}
