---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vizier-pem
spec:
  selector:
    matchLabels:
      name: vizier-pem
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20
  template:
    metadata:
      labels:
        name: vizier-pem
        plane: data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: Exists
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: Exists
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      initContainers:
      - name: qb-wait
        # yamllint disable-line rule:line-length
        image: ghcr.io/pixie-io/pixie-oss-pixie-dev-public-curl:multiarch-7.87.0@sha256:f7f265d5c64eb4463a43a99b6bf773f9e61a50aaa7cefaf564f43e42549a01dd
        command: ['sh', '-c', 'set -x;
          URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz";
          until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
            echo "waiting for ${URL}";
            sleep 2;
          done;
          '
        ]
        env:
        - name: SERVICE_NAME
          value: "vizier-query-broker-svc"
        - name: SERVICE_PORT
          value: "50300"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: pem
        image: vizier-pem_image:latest
        args:
        - --disable_dwarf_parsing=1
          - --elf_reader_max_file_size=146800640
        - --stirling_socket_tracer_percpu_bw_scaling_factor=0
        - --stirling_socket_tracer_max_total_data_bw=104857600 # 100MB
        - --stirling_socket_tracer_max_total_control_bw=10485760 # 10MB
        env:
        - name: PX_STIRLING_HTTP_BODY_LIMIT_BYTES
          value: "4096"
        - name: PL_STIRLING_SOURCES
          value: "socket_tracer,process_stats"
        - name: PX_STIRLING_ENABLE_MUX_TRACING
          value: "0"
        - name: PX_STIRLING_ENABLE_NATS_TRACING
          value: "0"
        - name: PX_STIRLING_ENABLE_CASS_TRACING
          value: "0"
        - name: PX_STIRLING_ENABLE_DNS_TRACING
          value: "0"
        - name: PX_STIRLING_ENABLE_MUX_TRACING
          value: "0"
        - name: PX_STIRLING_ENABLE_TLS_TRACING
          value: "0"
        - name: PL_TABLE_STORE_HTTP_EVENTS_PERCENT
          value: "25"
        - name: PL_TABLE_STORE_DATA_LIMIT_MB
          value: "70"
        - name: PL_DATASTREAM_BUFFER_SPIKE_SIZE
          value: "20971520" # 20MB
        - name: PL_DATASTREAM_BUFFER_MAX_GAP_SIZE
          value: "5242880" # 5MB
        - name: PX_TOTAL_CONN_TRACKER_MEM_USAGE
          value: "52428800" # 50MB
        - name: TCMALLOC_SAMPLE_PARAMETER
          value: "1048576"
        - name: PL_CLIENT_TLS_CERT
          value: /certs/client.crt
        - name: PL_CLIENT_TLS_KEY
          value: /certs/client.key
        - name: PL_TLS_CA_CERT
          value: /certs/ca.crt
        - name: PL_DISABLE_SSL
          value: "false"
        - name: PL_HOST_PATH
          value: "/host"
        - name: PL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PL_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: pl-cluster-secrets
        - name: PL_VIZIER_ID
          valueFrom:
            secretKeyRef:
              key: cluster-id
              name: pl-cluster-secrets
              optional: true
        - name: PL_VIZIER_NAME
          valueFrom:
            secretKeyRef:
              key: cluster-name
              name: pl-cluster-secrets
              optional: true
        - name: PL_CLOCK_CONVERTER
          value: "default"
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
          privileged: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: certs
          mountPath: /certs
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: certs
        secret:
          secretName: service-tls-certs
