---
apiVersion: v1
data:
  PL_CLOUD_ADDR: {{ if .Values.cloudAddr }}"{{ .Values.cloudAddr }}"{{ else }}"withpixie.ai:443"{{ end }}
  PL_CLUSTER_NAME: "{{ .Values.clusterName }}"
  PL_UPDATE_CLOUD_ADDR: {{ if .Values.cloudUpdateAddr }}"{{ .Values.cloudUpdateAddr }}"{{ else }}"withpixie.ai:443"{{ end }}
kind: ConfigMap
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  creationTimestamp: null
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  name: pl-cloud-config
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: v1
data:
  PL_CUSTOM_ANNOTATIONS: "{{ .Values.customAnnotations }}"
  PL_CUSTOM_LABELS: "{{ .Values.customLabels }}"
  PL_DISABLE_AUTO_UPDATE: {{ if .Values.disableAutoUpdate }}"{{ .Values.disableAutoUpdate }}"{{ else }}"false"{{ end }}
  PL_ETCD_OPERATOR_ENABLED: {{ if .Values.useEtcdOperator }}"true"{{else}}"false"{{end}}
  PL_MD_ETCD_SERVER: https://pl-etcd-client.{{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}.svc:2379
  PX_MEMORY_LIMIT: "{{ .Values.pemMemoryLimit }}"
  PX_MEMORY_REQUEST: "{{ .Values.pemMemoryRequest }}"
kind: ConfigMap
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  creationTimestamp: null
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  name: pl-cluster-config
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  creationTimestamp: null
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  name: pl-cluster-secrets
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
stringData:
  sentry-dsn: "{{ .Values.sentryDSN }}"
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{if .Values.customAnnotations}}{{range $element := split "," .Values.customAnnotations -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  creationTimestamp: null
  labels:
    {{if .Values.customLabels}}{{range $element := split "," .Values.customLabels -}}
    {{ $kv := split "=" $element -}}
    {{if eq (len $kv) 2 -}}
    {{ $kv._0 }}: "{{ $kv._1 }}"
    {{- end}}
    {{end}}{{end}}
  name: pl-deploy-secrets
  namespace: {{ if .Release.Namespace }}{{ .Release.Namespace }}{{ else }}pl{{ end }}
stringData:
  deploy-key: "{{ .Values.deployKey }}"
