---
# Note: The elastic-internal-suspend container is automatically injected by ECK.
# To control its resources, you may need to use ECK-specific configuration or
# modify the ECK operator deployment settings.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: pl-elastic
spec:
  version: 9.0.4
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
      node.store.allow_mmap: true
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs/module: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        initContainers:
        - name: sysctl
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
        - name: elastic-internal-init-filesystem
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 0Gi  # this is replaced by version specific patches
  - name: data
    # We need atleast 1 more than the number of index replicas we desire so that
    # pods can be disrupted for nodepool upgrades.
    count: 5
    config:
      node.roles: ["data", "ingest"]
      node.store.allow_mmap: true
      node.attr.data: hot
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs/module: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - SYS_CHROOT
              - SETUID
              drop:
              - ALL
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        initContainers:
        - name: sysctl
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 50m
        - name: elastic-internal-init-filesystem
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 0Gi  # this is replaced by version specific patches
